FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04

RUN apt-get update && apt-get install -y libboost-all-dev \
                                         libgoogle-perftools-dev

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN apt-get update

RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 
RUN conda --version
RUN conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
RUN conda install -c dglteam dgl-cuda10.2
RUN pip install requests

RUN pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu102.html \
    pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cu102.html  \
    pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.0+cu102.html \
    pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.0+cu102.html \
    pip install torch-geometric

RUN conda init
RUN /bin/bash -c "source root/.bashrc"

WORKDIR /GNNA

